name: tao_dividends

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app

  redis:
    image: redis:7.4-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  worker:
    build: .
    command: celery -A app.celery.celery worker --loglevel=info
    depends_on:
      - redis
    env_file:
      - .env

volumes:
  redis_data: